// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R4SsjYQl5MAd2bhlcP8ip9BpKF8E6kI',
    appId: '1:320635427911:web:5145c1ec4a652a15176562',
    messagingSenderId: '320635427911',
    projectId: 'foode-food-delivery',
    authDomain: 'foode-food-delivery.firebaseapp.com',
    storageBucket: 'foode-food-delivery.firebasestorage.app',
    measurementId: 'G-TM7KQ8RWHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8R5hGFp7h-Zs6Kq6B1uOb8hUPJl0zmxQ',
    appId: '1:320635427911:android:37c5e6be75fd008e176562',
    messagingSenderId: '320635427911',
    projectId: 'foode-food-delivery',
    storageBucket: 'foode-food-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zizRduapAQ_WiEVJvf_TGnV8SeW9r8o',
    appId: '1:320635427911:ios:fce50eba2cf63151176562',
    messagingSenderId: '320635427911',
    projectId: 'foode-food-delivery',
    storageBucket: 'foode-food-delivery.firebasestorage.app',
    iosBundleId: 'uz.itwithnurmuhammad.taskForUicgroup',
  );
}
